from app.state import BlogState


def blog_assembler(state: BlogState):

    print("\nAssembling blog...")

    plan = state["plan"]
    content_raw = state.get("content", {})
    content = content_raw[0] if isinstance(content_raw, list) and len(content_raw) > 0 else (content_raw if isinstance(content_raw, dict) else {})
    
    code_raw = state.get("code", {})
    code = code_raw[0] if isinstance(code_raw, list) and len(code_raw) > 0 else (code_raw if isinstance(code_raw, dict) else {})
    
    images_raw = state.get("images", {})
    images = images_raw[0] if isinstance(images_raw, list) and len(images_raw) > 0 else (images_raw if isinstance(images_raw, dict) else {})
    parts = []

    # Title
    parts.append(f"# {plan.title}")

    # Introduction
    if "Introduction" in content:
        parts.append("## Introduction")
        parts.append(content["Introduction"])

    # Main sections
    for section in plan.sections:

        title = section.title

        # Section heading
        parts.append(f"## {title}")

        # Section content
        if title in content:
            parts.append(content[title])


        # Code
        if title in code:

            generated_code = code[title]

            parts.append(
                f"### Example: {title}"
            )

            explanation = (
                getattr(generated_code, "explanation", None)
                if not isinstance(generated_code, dict)
                else generated_code.get("explanation")
            ) or ""
            parts.append(explanation)

            dependencies = (
                getattr(generated_code, "dependencies", None)
                if not isinstance(generated_code, dict)
                else generated_code.get("dependencies")
            ) or []

            if dependencies:

                deps_fmt = "\n".join(
                    f"- `{dependency}`"
                    for dependency in dependencies
                )

                parts.append(
                    "### Dependencies\n\n"
                    + deps_fmt
                )

            language = (
                getattr(generated_code, "language", None)
                if not isinstance(generated_code, dict)
                else generated_code.get("language")
            ) or "python"

            code_text = (
                getattr(generated_code, "code", None)
                if not isinstance(generated_code, dict)
                else generated_code.get("code")
            ) or ""

            parts.append(
                f"```{language}\n"
                f"{code_text}\n"
                f"```"
            )

        # Images
         # Diagram (SVG)
        if title in images:
            image = images[title]
 
            if image["status"] == "downloaded":
                # Embed SVG inline via markdown image syntax
                # (works in most markdown renderers and static site generators)
                parts.append(f"![{title}]({image['path']})")
                parts.append("*Diagram generated by AI.*")
 
            else:
                # Failed — leave an HTML comment so the author knows
                parts.append(
                    f"<!-- Diagram unavailable for '{title}': "
                    f"{image.get('error', 'unknown error')} -->"
                )

    # Conclusion
    if "Conclusion" in content:
        parts.append("## Conclusion")
        parts.append(content["Conclusion"])

    final_blog = "\n\n".join(parts)

    return {
        "final_blog": final_blog
    }